### ISSUE TITLE
[Bug] Large prompts get truncated on info modal

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [TheMurusTeam/PromptToImage#14]
### Problem

When using large prompts, as SD 2.1 seems to like very detailed descriptions, the prompt information gets truncated. 

### Possible solution
Insert the whole prompt (as it is there, by checking the EXIF data) 
or 
**Create a reuse this prompt feature that fetches the whole prompt**

**Comment by TheMurusTeam** [comment]
Fixed in build 6
