### ISSUE TITLE
When Creating Multiple Images They All Use the Same Seed

### ISSUE THREAD

**Issue by rhuddlestone** [TheMurusTeam/PromptToImage#3]
Hi

Nice work on the app, works great.  

When creating multiple images it creates them as a batch all using the same seed.  Not really a problem but it would be nice to be able to create multiple images from a prompt that each uses a random seed.

Thanks

**Comment by TheMurusTeam** [comment]
Yes, you are absolutely right, I'm working on it. Thanks!

**Comment by TheMurusTeam** [comment]
Fixed in build 5
