### ISSUE TITLE
Save and restore the last used compute unit

### ISSUE THREAD

**Issue by serovar** [TheMurusTeam/PromptToImage#4]
I think it would be better if PromptToImage kept the compute unit in use when reloading the app or changing the model (i.e. if I am using CPU & NE I don't want it to switch to CPU & GPU every time I switch the model or restart the app).

**Comment by TheMurusTeam** [comment]
It's already like this. App saves last used compute unit when quitting the app. However it does not work if you force quit it. Then, by default, when switching model the default compute unit is restored (cpu and gpu). This is to avoid issues if you switch to an -ORIGINAL model while using 'cpu and neural engine' (It will hang). You can change this unchecking the 'Always select default compute units when switching model' option. If unchecked, compute units will be preserved while switching model.
